export const SET_AUTHOR = 'SET_AUTHOR'

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'

export const SET_FAVORITE_LIST = 'SET_FAVORITE_LIST'

export const SET_FAVORITE_COLUMNIST = 'SET_FAVORITE_COLUMNIST'
